services:
  frontend:
    image: frontend-app
    ports:
      - "5000:5000"
    depends_on:
      - backend

  backend:
    image: backend-app
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis_db
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    depends_on:
      - db

  redis_db:
    image: redis:latest

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  reverse-proxy:
    image: nginx:stable-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend


